[workspace]
resolver = "3"
members = ["dyn_cfg", "dyn_cfg_macros", "examples/macros"]
author = ["badcw <badcw123@gmail.com>"]

[workspace.package]
version = "0.1.0"
edition = "2024"
publish = ["crates-io"]
repository = "https://github.com/badawsome/dyn-cfg-rs"
description = "Dynamic configuration refresh facades and macros"

[workspace.dependencies]
dyn_cfg_macros = { path = "./dyn_cfg_macros" }
futures = { version = "0.3.31" }
faststr = { version = "0.2.31" }
anyhow = { version = "1" }
thiserror = { version = "2.0.12" }
serde = { version = "1.0" }
serde_json = { version = "1.0" }
tokio = { version = "1.0", features = ["rt", "sync", "time"] }
tracing = { version = "0.1.40" }
